GET http://localhost:3000/products.json
Content-Type: application/json

{
  "id": 13
}

###

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Book", 
  "price": 35.00, 
  "image_url": "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cmVhZGluZyUyMGJvb2t8ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80", 
  "description": "A place to lose yourself for extended periods of time in a different universe."
}

###  UPDATE

PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
  "name": "Pen", 
  "price": 5.99, 
  "image_url": "https://m.media-amazon.com/images/I/71LbzzDezeL._AC_SY355_.jpg",
  "description": "The mightiest weapon in the world now on sale for only 5.99!"
}

### DELETE

DELETE http://localhost:3000/products/17.json
Content-Type: application/json