POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Pen", 
  "price": 5.99, 
  "image_url": "https://m.media-amazon.com/images/I/71LbzzDezeL._AC_SY355_.jpg",
  "description": "The mightiest weapon in the world now on sale for only 5.99!"
}

###  UPDATE

PATCH http://localhost:3000/products/16.json
Content-Type: application/json

{
  "image_url": "nil",
  "description": "A mythical thing being sold only for a short time!"
}

### DELETE

DELETE http://localhost:3000/products/16.json
Content-Type: application/json